title: Justin Flick
description: >-
  Musings on Data Science/Engineering, Software Development, and Corporate Management.
author: Justin Flick
baseurl: ""
url: "https://justinflick.com"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
google_analytics: G-WVPX2KDWCZ
minima:
  social_links:
    - platform: github
      user_url: "https://github.com/Jflick58"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/justin-flick-88416b71/"
